[package]
name = "chat_stream_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.25.0", features = ["full"] }
futures = "0.3.26"
async-openai = "0.15.0"
dotenv = "0.15.0"
